[package]
name = "website"
version = "0.1.0"
authors = ["Robert Snakard <robert.snakard@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tera = '*'
